apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-api
  namespace: default
  labels:
    app: pipeline-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pipeline-api
  template:
    metadata:
      labels:
        app: pipeline-api
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: db-migration
          image: ghcr.io/klimatbyran/pipeline-api
          command: ['npm', 'run', 'migrate']
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/pipeline-api
      containers:
        - name: pipeline-api
          image: ghcr.io/klimatbyran/pipeline-api
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/pipeline-api
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: env
                  key: API_SECRET
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: REDIS_HOST
              value: redis-master
            - name: CHROMA_HOST
              value: http://chromadb:8000
            - name: FRONTEND_URL
              value: https://frontend.myapp.com
imagePullPolicy: Always