apiVersion: batch/v1
kind: CronJob
metadata:
  name: pipeline-api-prune-runs
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: prune-runs
              image: ghcr.io/klimatbyran/pipeline-api
              command: ["npm", "run", "prune-runs-by-company"]
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redis
                      key: redis-password
                - name: REDIS_HOST
                  value: redis-master.garbo-stage.svc.cluster.local
                - name: INTERNAL_SERVICE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: env
                      key: INTERNAL_SERVICE_TOKEN
                - name: NODE_ENV
                  valueFrom:
                    secretKeyRef:
                      name: env
                      key: NODE_ENV
